### ISSUE TITLE
No pdf output.

### ISSUE THREAD

**Issue by jolo2000** [quorak/grails-wkhtmltopdf#2]
Hello 

am trying use the Grails wkhtmltopdf plugin but i can't get a rendered pdf file. Only the gsp template is shown instead.

What I have done so far:

This is the link, which calls the action in the Controller:

<pre><code data-language="groovy">
g:link action='downloadQuestionnaire' id="${questionnaireInstance?.id}">Download questionnaire /g:link
</code></pre>

This is the action in the Controller:

<pre><code>
def downloadQuestionnaire = {
    def questionnaire = Questionnaire.get(params.id) 

    render( filename:"File ${questionnaire.id}.pdf",
    view:'/templates/pdf/_questionnaire.gsp',
    model:[questionnaireInstance: questionnaire],
    marginLeft:20,
    marginTop:35,
    marginBottom:20,
    marginRight:20,
    headerSpacing:10,
    )
}
</code></pre>

_questionnaire.gsp is the template, which should be rendered as pdf.

In config.groovy

<pre><code>
grails.plugin.wkhtmltox.binary = "/usr/local/bin/wkhtmltopdf"
</code></pre>

and i checked, that wkhtmltopdf ist working correctly.

To my understanding of the wkhtmltopdf plugin, the template _questionnaire.gsp should be rendered as pdf available to download. But in my case, the gsp-template is shown with the data of the questionnaireInstance. There are no error messages at all.

Any ideas, how to get the pdf output?

Yours Johannes

**Comment by dhaval87** [comment]
For me also ,only the rendered template is shown. same as you I tried to download wkhtmltopdf from http://code.google.com/p/wkhtmltopdf/downloads/detail?name=wkhtmltopdf.dmg but now that is not working as well.
What to do what is solution ? even wkhtmltoxService gives error for me, though wkhtmltopdf www.google.de test.pdf works fine for me....
